In [7]:
def divide(dividend ,divisor ):
    try:
        result=dividend/divisor
        print("The quotient of {} divided by {} is :{} ".format(dividend,divisor,result))
    except ZeroDivisionError :
        print("Division by Zero")
    pass
dividend = float(input("Enter the Divendend number: "))
divisor = float(input("Enter the Divisor number: "))
divide(dividend,divisor)

Enter the Divendend number: 5
Enter the Divisor number: 3
The quotient of 5.0 divided by 3.0 is :1.6666666666666667 


In [19]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            print(i,j,k)
#[print(i,j,k) for i in subjects for j in verbs for k in objects]

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [3]:
import numpy as np
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [4]:
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [5]:
x = np.array([1, 2, 3, 5])
np.vander(x)


array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [6]:
np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])